name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Validate JSON Resume
        uses: lukew3/validate-json-resume-action@v1
        with:
          resume-path: resume.json
